#
# ansible software setup playbook
# update the software for the rov
#
# an internet connection is required for this playbook to run
#
---
- name: Hydrozoa ROV software prep
  become: yes
  hosts: all
  tasks:

  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
      allow_unauthenticated: yes

  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes
      allow_unauthenticated: yes

  - name: apt install depends
    ansible.builtin.apt:
      name:
      - net-tools
      - ipython3
      - python3-pip
      - python3-smbus

  - name: pip install depends
    ansible.builtin.pip:
      name:
      - pigpio
      - adafruit-circuitpython-servokit
      - adafruit-circuitpython-lsm6ds

  - name: add ros apt repo key
    ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc

  - name: add ros apt repo
    ansible.builtin.apt_repository:
      repo: deb http://packages.ros.org/ros/ubuntu focal main

  - name: apt install ros (THIS MAY TAKE A WHILE)
    ansible.builtin.apt:
      name:
      - ros-noetic-desktop-full

  - name: apt install ros extensions
    ansible.builtin.apt:
      name:
      - ros-noetic-robot-pose-ekf
      - ros-noetic-robot-localization
      - ros-noetic-imu-filter-madgwick
      - python3-rosdep
      - python3-rosinstall
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
      - ros-noetic-joy
      #- ros-noetic-joystick-drivers
      - ros-noetic-robot-localization
      - ros-noetic-usb-cam
