#
# ansible_playbook_rov.yml
#
---

- name: apt update & upgrade
  become: yes
  hosts: hydrozoa
  tags: apt-setup
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes

- name: install dependancies
  become: yes
  hosts: hydrozoa
  tags: apt-depends
  tasks:
  - name: apt install depends
    ansible.builtin.apt:
      name:
      - net-tools
      - ipython3
      - python3-pip
      - python-smbus
      - raspi-config
      - rpi-update
  - name: install pip depends
    ansible.builtin.pip:
      name:
      - adafruit-circuitpython-servokit
      - adafruit-circuitpython-lsm6ds

- name: git
  hosts: hydroza
  tasks:
  - name: git clone cabrillo_rov
    ansible.builtin.git:
      dest: /home/pi/cabrillo_rov
      repo: https://github.com/cabrillorobotics/cabrillo_rov.git
      track_submodules: yes

- name: apt repo and key
  become: yes
  hosts: hydrozoa
  tags: apt-repo-key
  tasks:
  - name: add ros apt repo
    ansible.builtin.apt_repository:
      repo: deb http://packages.ros.org/ros/ubuntu focal main
  - name: apt add repo key
    ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc

- name: install ros
  become: yes
  hosts: hydrozoa
  tags: install-ros
  tasks:
  - name: apt install ros (THIS MAY TAKE A WHILE)
    ansible.builtin.apt:
      name:
      - ros-noetic-desktop-full
  - name: apt install ros extensions
    ansible.builtin.apt:
      name:
      - ros-noetic-robot-pose-ekf
      - ros-noetic-robot-localization
      - ros-noetic-imu-filter-madgwick
      - python3-rosdep
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
      - ros-noetic-joy
      - ros-noetic-joystick-drivers
      - ros-noetic-robot-localization
      - ros-noetic-usb-cam

- name: startup scripts
  hosts: hydrozoa
  tasks:
  - name: add startup script to crontab
    ansible.builtin.cron:
      name: rov_startup
      special_time: reboot
      job: /home/ubuntu/cabrillo_rov/misc/rov_startup.sh >/tmp/scriptLog

- name: hardware config
  hosts: hydrozoa
  become: yes
  tasks:
  - name: enable i2c
    ansible.builtin.lineinfile:
      path: /etc/udev/rules.d/99-com.rules
      line: SUBSYSTEM=="ic2-dev", GROUP="i2c", MODE="0660"
  - name: i2c device permissions
    ansible.builtin.file:
      path: /dev/i2c-1
      group: i2c
      mode: g+rw

  