#
# ansible_playbook_rov.yml
#
---

- name: Hydrozoa ROV software
  import_playbook: tasks/software.yml

- name: hydrozoa rov download cabrillo_rov git repo
  hosts: all
  tags: git-repo
  tasks:

  - name: git clone or pull cabrillo_rov
    ansible.builtin.git:
      dest: /home/{{ansible_user}}/cabrillo_rov
      repo: https://github.com/cabrillorobotics/cabrillo_rov.git
      track_submodules: yes


- name: hydrozoa rov pi hardware config
  hosts: hydrozoa
  become: yes
  tasks:

  - name: add ubuntu to i2c group
    ansible.builtin.user:
      append: yes
      groups: i2c
      name: ubuntu

  - name: rosdep init
    ansible.builtin.shell:
      chdir: /home/{{ansible_user}}/cabrillo_rov
      cmd: rosdep init && rosdep update
    ignore_errors: yes

  - name: enable i2c
    ansible.builtin.lineinfile:
      path: /etc/udev/rules.d/99-com.rules
      create: yes
      line: SUBSYSTEM=="ic2-dev", GROUP="i2c", MODE="0660"

  - name: add pigpio service
    ansible.builtin.blockinfile:
      path: /lib/systemd/system/pigpiod.service
      create: yes
      block: |
        [Unit]
        Description=Daemon required to control GPIO pins via pigpio
        [Service]
        ExecStart=/usr/local/bin/pigpiod
        ExecStop=/bin/systemctl kill -s SIGKILL pigpiod
        Type=forking
        [Install]
        WantedBy=multi-user.target

  - name: add startup playbook to root crontab
    ansible.builtin.cron:
      name: ansible_playbook_rov_startup.yml
      special_time: reboot
      job: source /home/ubuntu/cabrillo_rov/misc/rov_startup.sh

  - name: add ros setup to bashrc
    ansible.builtin.lineinfile:
      path: /home/{{ansible_user}}/.bashrc
      line: source /opt/ros/noetic/setup.bash

  - name: reboot hydrozoa
    ansible.builtin.reboot:

