#
# ansible_playbook_rov.yml
#
---

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: ansible_user_local

- name: install dependancies
  become: yes
  become_user: root
  hosts: all
  tasks:

  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
      allow_unauthenticated: yes

  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes
      allow_unauthenticated: yes

  - name: apt install depends
    ansible.builtin.apt:
      name:
      - net-tools
      - ipython3
      - python3-pip
      - python3-smbus
      - vim
      - sysfsutils

  - name: apt remove packages
    ansible.builtin.apt:
      state: absent
      name:
      - unattended-upgrades

  - name: pip install depends
    ansible.builtin.pip:
      state: latest
      name:
      - setuptools
      - adafruit-python-shell
      - pigpio
      - adafruit-circuitpython-pca9685
      - adafruit-circuitpython-servokit
      - adafruit-circuitpython-lsm6ds
      - adafruit-circuitpython-lis3mdl
      - adafruit-circuitpython-mpu6050

  - name: add ros apt repo key
    ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc

  - name: add ros apt repo
    ansible.builtin.apt_repository:
      repo: deb http://packages.ros.org/ros/ubuntu focal main

  - name: apt install ros (THIS MAY TAKE A WHILE)
    ansible.builtin.apt:
      name:
      - ros-noetic-desktop-full


- name: install supplimentary software
  become: true
  hosts: all
  tasks:

  - name: apt install ros extensions
    ansible.builtin.apt:
      name:
      - ros-noetic-robot-pose-ekf
      - ros-noetic-robot-localization
      - ros-noetic-imu-filter-madgwick
      - python3-rosdep
      - python3-rosinstall
      - python3-rosinstall-generator
      - python3-wstool
      - python3-rospy
      - build-essential
      - ros-noetic-joy
      #- ros-noetic-joystick-drivers # this appears to be depricated
      - ros-noetic-robot-localization
      - ros-noetic-usb-cam
      - ros-noetic-geometry-msgs
      - ros-noetic-sensor-msgs

  - name: rosdep init
    become: yes
    become_user: root
    ansible.builtin.shell:
      cmd: rosdep init
    ignore_errors: yes

  - name: rosdep update
    become: yes
    become_user: "{{ansible_user}}"
    ansible.builtin.shell:
      cmd: rosdep update
    ignore_errors: yes


- name: download cabrillo_rov git repo in home folder
  hosts: all
  tags: git-repo
  tasks:
  
  - name: git clone or pull cabrillo_rov
    ansible.builtin.git:
      dest: /home/{{ansible_user}}/cabrillo_rov
      repo: https://github.com/cabrillorobotics/cabrillo_rov.git
      track_submodules: yes


- name: shore hardware configs
  hosts: shore
  tasks:
  - name: disable dell acceleromiter
    ansible.builtin.blockinfile:
      path: /etc/modprobe.d/blacklist.conf
      block: |
        blacklist lis3lv02d_i2c
        blacklist lis3lv02d
  - name: disable bluetooth ertm (so bluetooth xbox works)
    ansible.builtin.blockinfile:
      path: /etc/sysfs.conf
      block: /module/bluetooth/parameters/disable_ertm=1

- name: rov pigpiod setup
  hosts: rov
  tasks:
  - name: download and unarchive source code
    ansible.builtin.unarchive:
      remote_src: yes
      src: https://github.com/joan2937/pigpio/archive/master.zip
      dest: /home/ubuntu/
  - name: build pigpio (make)
    community.general.make:
      chdir: /home/ubuntu/pigpio-master/
  - name: make install
    become: yes
    become_user: root
    community.general.make:
      chdir: /home/ubuntu/pigpio-master/
      target: install
# pigpiod service file https://forums.raspberrypi.com/viewtopic.php?t=319761
  - name: add pigpio service
    become: yes
    become_user: root
    ansible.builtin.blockinfile:
      path: /lib/systemd/system/pigpiod.service
      create: yes
      owner: root
      group: root
      mode: 644
      marker: ""
      marker_begin: ""
      marker_end: ""
      block: |
        [Unit]
        Description=Daemon required to control GPIO pins via pigpio
        [Service]
        ExecStart=/usr/local/bin/pigpiod
        ExecStop=/bin/systemctl kill -s SIGTERM pigpiod
        Type=forking
        [Install]
        WantedBy=multi-user.target
  - name: systemd enable pigpiod
    become: yes
    become_user: root
    ansible.builtin.systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: pigpiod.service


- name: hydrozoa rov pi hardware config
  hosts: rov
  become: yes
  tasks:

  - name: add ubuntu to i2c group
    ansible.builtin.user:
      append: yes
      groups: i2c
      name: ubuntu

  - name: enable i2c
    ansible.builtin.lineinfile:
      path: /etc/udev/rules.d/99-com.rules
      create: yes
      line: SUBSYSTEM=="ic2*", GROUP="i2c", MODE="0660"

  - name: add startup script to ubuntu crontab
    ansible.builtin.cron:
      user: ubuntu
      name: rov startup script
      special_time: reboot
      job: /home/ubuntu/cabrillo_rov/misc/rov_startup.sh > /tmp/rov_startup_stdout 2> /tmp/rov_startup_stderr

  - name: add ros setup to bashrc
    ansible.builtin.blockinfile:
      marker: "# cabrillo_rov ansible"
      path: /home/{{ansible_user}}/.bashrc
      block: source /opt/ros/noetic/setup.bash

  - name: reboot hydrozoa
    ansible.builtin.reboot:

