#
# DEPRICATED - DO NOT USE
# 
# Cabrillo College Hydrozoa ROV
# ansible_playbook_rov_startup.yml
# 
# ansible playbook to be run by root's crontab on pi reboot
#
---

- name: Hydrozoa ROV startup playbook
  become: yes
  local_action:

  - name: update i2c device permissions
    ansible.builtin.file:
      path: /dev/i2c-1
      group: i2c
      mode: g+rw
  
  - name: ros setup script
    ansible.builtin.shell:
      cmd: source /opt/ros/noetic/setup.bash
  
  - name: start roscore
    ansible.builtin.shell:
      cmd: roscore
  
  - name: ros catkin make
    ansible.builtin.shell:
      chdir: /home/ubuntu/cabrilo_rov
      cmd: catkin_make
  
  - name: ros devel setup
    ansible.builtin.shell:
      chdir: /home/ubuntu/cabrilo_rov
      cmd: source ./devel/setup.bash
  
  - name: roslaunch
    ansible.builtin.shell:
      chdir: /home/ubuntu/cabrilo_rov
      cmd: roslaunch ./launch/rov.launch