#
# ansible_playbook_rov.yml
#
---

- name: apt update & upgrade
  become: yes
  hosts: hydrozoa
  tags: apt-setup
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes

- name: apt install depends
  become: yes
  hosts: hydrozoa
  tags: apt-depends
  tasks:
  - name: apt install depends
    ansible.builtin.apt:
      name:
      - net-tools
      - ipython3

- name: apt repo and key
  become: yes
  hosts: hydrozoa
  tags: apt-repo-key
  tasks:
  - name: add ros apt repo
    ansible.builtin.apt_repository:
      repo: deb http://packages.ros.org/ros/ubuntu focal main
  - name: apt add repo key
    ansible.builtin.apt_key:
      url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc

- name: install ros
  become: yes
  hosts: hydrozoa
  tags: install-ros
  tasks:
  - name: apt install ros (THIS MAY TAKE A WHILE)
    ansible.builtin.apt:
      name:
      - ros-noetic-desktop-full
  - name: apt install ros extensions
    ansible.builtin.apt:
      name:
      - ros-noetic-robot-pose-ekf
      - ros-noetic-robot-localization
      - ros-noetic-imu-filter-madgwick
      - python3-rosdep
      - python3-rosinstall-generator
      - python3-wstool
      - build-essential
      - ros-noetic-joy
      - ros-noetic-joystick-drivers
